version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URI=mysql+pymysql://${USER_DB}:${PASSWORD_DB}@db:3306/${NAME_DB}
      - SECRET_KEY=${SECRET_KEY}
    command: >
      bash -c "
        flask db upgrade &&
        flask run --host=0.0.0.0 --port=5000
      "
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app  # Gắn kết mã nguồn từ host vào container
      - /app/__pycache__  # Tránh lưu cache bên trong container

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_DB}
      MYSQL_DATABASE: ${NAME_DB}
      MYSQL_USER: ${USER_DB}
      MYSQL_PASSWORD: ${PASSWORD_DB}
    expose:
      - 3306
    volumes:
      - /tmp/app/mysqld:/run/mysqld
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    

volumes:
  db_data:
