"""Add splited field to Video model

Revision ID: 5f9e13ed31d7
Revises: 
Create Date: 2025-01-23 21:43:21.185718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9e13ed31d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('facebook_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facebook_user_id', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facebook_user_id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=310), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facebook_ad_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facebook_ad_account_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_status', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('amount_spent', sa.Float(), nullable=True),
    sa.Column('spend_cap', sa.Float(), nullable=True),
    sa.Column('timezone_name', sa.String(length=100), nullable=True),
    sa.Column('timezone_offset_hours_utc', sa.Float(), nullable=True),
    sa.Column('business_id', sa.String(length=255), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('facebook_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facebook_account_id'], ['facebook_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('page_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('facebook_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facebook_account_id'], ['facebook_account.id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('facebook_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facebook_account_id'], ['facebook_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_playlist',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'playlist_id')
    )
    op.create_table('facebook_campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facebook_campaign_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('facebook_account_id', sa.Integer(), nullable=False),
    sa.Column('facebook_ad_account_id', sa.Integer(), nullable=False),
    sa.Column('special_ad_categories', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['facebook_account_id'], ['facebook_account.id'], ),
    sa.ForeignKeyConstraint(['facebook_ad_account_id'], ['facebook_ad_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facebook_campaign_id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('crawled', sa.Boolean(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('splited', sa.Boolean(), nullable=True),
    sa.Column('facebook_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facebook_account_id'], ['facebook_account.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_category',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('video_id', 'category_id')
    )
    op.create_table('video_split',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('type_duration', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('facebook_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facebook_account_id'], ['facebook_account.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stack_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.String(length=255), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('video_split_id', sa.Integer(), nullable=False),
    sa.Column('posted_video_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('facebook_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facebook_account_id'], ['facebook_account.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.page_id'], ),
    sa.ForeignKeyConstraint(['video_split_id'], ['video_split.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_split_category',
    sa.Column('video_split_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['video_split_id'], ['video_split.id'], ),
    sa.PrimaryKeyConstraint('video_split_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_split_category')
    op.drop_table('stack_post')
    op.drop_table('video_split')
    op.drop_table('video_category')
    op.drop_table('video')
    op.drop_table('facebook_campaign')
    op.drop_table('category_playlist')
    op.drop_table('playlist')
    op.drop_table('page')
    op.drop_table('facebook_ad_accounts')
    op.drop_table('history')
    op.drop_table('facebook_account')
    op.drop_table('category')
    # ### end Alembic commands ###
